INSERT INTO roles (role) VALUES
('Student'),
('Faculty'),
('Staff'),
('Administrator'),
('Researcher'),
('Athlete'),
('Event Coordinator'),
('Teaching Assistant'),
('Guest Speaker'),
('Alumni'),
('Volunteer'),
('Security Personnel'),
('IT Support'),
('Club President'),
('Graduate Assistant'),
('Event Speaker'),
('Organizer'),
('Guest Attendee'),
('Program Director'),
('Department Head');
