INSERT INTO organizations (name, description, contact_info) VALUES
('Virginia Tech Athletics', 'Athletics Department', 'athletics@vt.edu'),
('VT Computer Science Department', 'Department of Computer Science', 'csdept@vt.edu'),
('Virginia Tech Alumni Association', 'Alumni Relations', 'alumni@vt.edu'),
('Student Government Association', 'Student Government', 'sga@vt.edu'),
('Hokie Club', 'Virginia Tech Sports Club', 'hokieclub@vt.edu'),
('VT Research Institute', 'University Research and Development', 'research@vt.edu'),
('Virginia Tech Marching Virginians', 'University Marching Band', 'marchingvirginians@vt.edu'),
('VT Women\'s Soccer', 'Women\'s Soccer Team', 'womenssoccer@vt.edu'),
('Virginia Tech Career Services', 'Student Career Support', 'careerservices@vt.edu'),
('VT Dining Services', 'On-campus Dining Services', 'dining@vt.edu'),
('VT Performing Arts', 'University Performing Arts', 'performingarts@vt.edu'),
('VT Student Counseling Center', 'Student Counseling Services', 'counseling@vt.edu'),
('Hokie Nation', 'Virginia Tech Fans and Alumni Network', 'hokienation@vt.edu'),
('Virginia Tech College of Engineering', 'Engineering College at VT', 'coe@vt.edu'),
('VT International Programs', 'Study Abroad Programs', 'intlprograms@vt.edu'),
('Women in STEM at VT', 'Women in STEM Support', 'womeninstem@vt.edu'),
('VT Greenhouse', 'Sustainable Agriculture and Research', 'greenhouse@vt.edu'),
('Virginia Tech Theatre Department', 'Theater Arts Program', 'theatre@vt.edu'),
('Hokie Wellness', 'Health and Wellness at VT', 'hokiewellness@vt.edu'),
('VT Environmental Club', 'Environmental Awareness Club', 'enviroclub@vt.edu');
